const k = {
  PROJECT_ALREADY_CLAIMED: 'PROJECT_ALREADY_CLAIMED',
  ROW_NOT_FOUND: 'ROW_NOT_FOUND',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INCORRECT_CREDENTIALS: 'INCORRECT_CREDENTIALS',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  POSTGRES_UNIQUE_VIOLATION: '23505',
  UNAUTHORIZED_STATUS: 401,
  UNAUTHORIZED: 'UNAUTHORIZED',
  USER_TYPE: {
    PROFESSOR: 'PROFESSOR',
    STUDENT: 'STUDENT',
    ADMIN: 'ADMIN',
    UNSET: 'UNSET'
  },
  STRATEGY: {
    LOCAL: 'LOCAL',
    GOOGLE: 'GOOGLE',
    FACEBOOK: 'FACEBOOK',
    OPENID: 'OPENID'
  }
};

export default k;
