const k = {
  ROW_NOT_FOUND: 'ROW_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INCORRECT_CREDENTIALS: 'INCORRECT_CREDENTIALS',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND'
};

export default k;
