const k = {
  ROW_NOT_FOUND: 'ROW_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INCORRECT_CREDENTIALS: 'INCORRECT_CREDENTIALS',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  UNSET: 'UNSET',
  UNIQUE_VIOLATION: '23505',
  UNAUTHORIZED_STATUS: 401,
  UNAUTHORIZED: 'UNAUTHORIZED',
  PROFESSOR: 'PROFESSOR',
  STUDENT: 'STUDENT',
  ADMIN: 'ADMIN',
  STRATEGY: {
    LOCAL: 'LOCAL',
    GOOGLE: 'GOOGLE',
    FACEBOOK: 'FACEBOOK',
    OPENID: 'OPENID'
  }
};

export default k;
